import React, { useState } from "react";

import SingleSection from "../modules/SingleSection";

import "./Instructions.css";

type Props = {};

const Instructions = (props: Props) => {
  const [focusedSection, setFocusedSection] = useState(1);
  return (
    <div className="u-flex">
      <div className="Instructions-sidebar"></div>
      <div className="Instructions-container">
        <div className="Instructions-paddingDiv">
          <SingleSection
            id={1}
            title="From Hyperboloid to Canton Tower"
            content="In Mathematics, a hyperboloid of revolution, sometimes called a circular hyperboloid, is the surface generated by rotating a hyperbola around one of its principle axes. A hyperboloid is the surface obtained from a hyperboloid of revolution by deforming it by means of  directional scalings, or more generally, of an affine transformation."
            isFocused={focusedSection === 1}
          />
          <SingleSection
            id={2}
            title="From Hyperboloid to Canton Tower"
            content="In Mathematics, a hyperboloid of revolution, sometimes called a circular hyperboloid, is the surface generated by rotating a hyperbola around one of its principle axes. A hyperboloid is the surface obtained from a hyperboloid of revolution by deforming it by means of  directional scalings, or more generally, of an affine transformation."
            isFocused={focusedSection === 2}
          />
        </div>
      </div>
    </div>
  );
};

export default Instructions;
