import React, { useState } from "react";

import SectionCard from "../modules/SectionCard";
import DemoHyperboloid from "../modules/demostrations/DemoHyperboloid";

import "./Introduction.css";

type Props = {};

const Introduction = (props: Props) => {
  const texts: [number, string, string][] = [
    [
      1,
      "From Hyperboloid to Canton Tower",
      "In Mathematics, a hyperboloid of revolution, sometimes called a circular hyperboloid, is the surface generated by rotating a hyperbola around one of its principle axes. A hyperboloid is the surface obtained from a hyperboloid of revolution by deforming it by means of  directional scalings, or more generally, of an affine transformation.",
    ],
    [
      2,
      "Build Canton Tower with Hands",
      "The Canton Tower is a famous building in Guangzhou, and its tower body is a hyperboloid of revolution. Inspired by mathematics, we can control the central circle radius and the inclination of the waist of the Guangzhou Tower. In this application, we will use hands to build it.",
    ],
    [
      3,
      "Login to Save Your Work",
      "After the construction is completed, you can also choose to log in to save your work.",
    ],
  ];

  const cardList = texts.map((text) => (
    <SectionCard key={text[0]} id={text[0]} title={text[1]} content={text[2]} />
  ));

  return (
    <div className="u-flex">
      <div className="Introduction-sidebar">
        <DemoHyperboloid />
      </div>
      <div className="Introduction-container u-flexColumn">{cardList}</div>
    </div>
  );
};

export default Introduction;
